name: Test

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    name: '${{ matrix.os }} Python ${{ matrix.python-version }}'
    runs-on: ${{ matrix.os }}
    env:
      PYTHONUNBUFFERED: 1
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # TODO: macOS-latest, windows-latest
        python-version: ["3.10", "3.9", "3.8", "3.7"]
    steps:
    - uses: actions/checkout@v2
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v2
      with:
        python-version: '${{ matrix.python-version }}'

    - name: 'Install package'
      run: |
        make install-poetry
        poetry lock
        poetry show --tree
        make install

    - name: 'List installed packages'
      run: |
        poetry run pip freeze

    - name: 'Run tests on ${{ matrix.os }} with Python ${{ matrix.python-version }}'
      run: |
        make pytest-ci

    - name: 'Upload coverage report'
      run: bash <(curl -s https://codecov.io/bash)

    - name: 'Run linters'
      if: matrix.python-version == '3.8'
      run: |
        make lint
